apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoother-deployment
  labels:
    app: smoother
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smoother
  template:
    metadata:
      labels:
        app: smoother
    spec:
      containers:
      - name: smoother
        image: index.docker.io/elizaslavchik/smoother:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "500Mi"
            cpu: 0.5
          requests:
            memory: "200Mi"
            cpu: 0.1

