apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoother
  labels:
    app: smoother
spec:
  replicas: 4
  selector:
    matchLabels:
      app: smoother
  template:
    metadata:
      labels:
        app: smoother
    spec:
      containers:
      - name: smoother
        image: index.docker.io/elizaslavchik/smoother:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /smoother/health/is-alive
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10       
 