apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoother-algo
  labels:
    app: smoother-algo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smoother-algo
  template:
    metadata:
      labels:
        app: smoother-algo
    spec:
      containers:
      - name: smoother-algo
        image: index.docker.io/elizaslavchik/smoother-algo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /smoother-algo/health/is-alive
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 10        
 